import { Class } from "./augmented-types/techniques";
import {
  TypeMatchupSquare,
  TypeMatchups,
  TypeElement,
} from "./augmented-types/temtems";
import matchupAlteringTraitsJSON from "./special-case-data/matchup-altering-traits.json";

export const typeMatchupSquare: TypeMatchupSquare = {
  Neutral: {
    Neutral: 1,
    Wind: 1,
    Earth: 1,
    Water: 1,
    Fire: 1,
    Nature: 1,
    Electric: 1,
    Mental: 0.5,
    Digital: 1,
    Melee: 1,
    Crystal: 1,
    Toxic: 1,
  },
  Wind: {
    Neutral: 1,
    Wind: 0.5,
    Earth: 1,
    Water: 1,
    Fire: 1,
    Nature: 1,
    Electric: 0.5,
    Mental: 1,
    Digital: 1,
    Melee: 1,
    Crystal: 1,
    Toxic: 2,
  },
  Earth: {
    Neutral: 1,
    Wind: 0.5,
    Earth: 1,
    Water: 0.5,
    Fire: 2,
    Nature: 0.5,
    Electric: 2,
    Mental: 1,
    Digital: 1,
    Melee: 1,
    Crystal: 2,
    Toxic: 1,
  },
  Water: {
    Neutral: 1,
    Wind: 1,
    Earth: 2,
    Water: 0.5,
    Fire: 2,
    Nature: 0.5,
    Electric: 1,
    Mental: 1,
    Digital: 2,
    Melee: 1,
    Crystal: 1,
    Toxic: 0.5,
  },
  Fire: {
    Neutral: 1,
    Wind: 1,
    Earth: 0.5,
    Water: 0.5,
    Fire: 0.5,
    Nature: 2,
    Electric: 1,
    Mental: 1,
    Digital: 1,
    Melee: 1,
    Crystal: 2,
    Toxic: 1,
  },
  Nature: {
    Neutral: 1,
    Wind: 1,
    Earth: 2,
    Water: 2,
    Fire: 0.5,
    Nature: 0.5,
    Electric: 1,
    Mental: 1,
    Digital: 1,
    Melee: 1,
    Crystal: 1,
    Toxic: 0.5,
  },
  Electric: {
    Neutral: 1,
    Wind: 2,
    Earth: 0.5,
    Water: 2,
    Fire: 1,
    Nature: 0.5,
    Electric: 0.5,
    Mental: 2,
    Digital: 2,
    Melee: 1,
    Crystal: 0.5,
    Toxic: 1,
  },
  Mental: {
    Neutral: 2,
    Wind: 1,
    Earth: 1,
    Water: 1,
    Fire: 1,
    Nature: 1,
    Electric: 1,
    Mental: 1,
    Digital: 1,
    Melee: 2,
    Crystal: 0.5,
    Toxic: 1,
  },
  Digital: {
    Neutral: 1,
    Wind: 1,
    Earth: 1,
    Water: 1,
    Fire: 1,
    Nature: 1,
    Electric: 1,
    Mental: 2,
    Digital: 2,
    Melee: 2,
    Crystal: 1,
    Toxic: 1,
  },
  Melee: {
    Neutral: 1,
    Wind: 1,
    Earth: 2,
    Water: 1,
    Fire: 1,
    Nature: 1,
    Electric: 1,
    Mental: 0.5,
    Digital: 1,
    Melee: 0.5,
    Crystal: 2,
    Toxic: 1,
  },
  Crystal: {
    Neutral: 1,
    Wind: 1,
    Earth: 0.5,
    Water: 1,
    Fire: 0.5,
    Nature: 1,
    Electric: 2,
    Mental: 2,
    Digital: 1,
    Melee: 1,
    Crystal: 1,
    Toxic: 1,
  },
  Toxic: {
    Neutral: 1,
    Wind: 1,
    Earth: 0.5,
    Water: 2,
    Fire: 1,
    Nature: 2,
    Electric: 1,
    Mental: 1,
    Digital: 0.5,
    Melee: 1,
    Crystal: 0.5,
    Toxic: 0.5,
  },
};

export const matchupAlteringTraits = new Map(
  matchupAlteringTraitsJSON.map((object) => {
    return [object.trait, object.modifier as TypeMatchups];
  })
);

export const typeElementIcons: Record<TypeElement, string> = {
  Neutral: "https://temtem.wiki.gg/images/b/b3/Neutral.png",
  Wind: "https://temtem.wiki.gg/images/b/bf/Wind.png",
  Earth: "https://temtem.wiki.gg/images/1/1e/Earth.png",
  Water: "https://temtem.wiki.gg/images/9/9d/Water.png",
  Fire: "https://temtem.wiki.gg/images/3/30/Fire.png",
  Nature: "https://temtem.wiki.gg/images/a/a7/Nature.png",
  Electric: "https://temtem.wiki.gg/images/2/2f/Electric.png",
  Mental: "https://temtem.wiki.gg/images/b/bf/Mental.png",
  Digital: "https://temtem.wiki.gg/images/1/1b/Digital.png",
  Melee: "https://temtem.wiki.gg/images/8/8f/Melee.png",
  Crystal: "https://temtem.wiki.gg/images/3/31/Crystal.png",
  Toxic: "https://temtem.wiki.gg/images/9/96/Toxic.png",
};

export const PRIORITY_ICON_URLS: Record<number, string> = {
  0: "https://temtem.wiki.gg/images/8/80/Priority_VeryLow.png",
  1: "https://temtem.wiki.gg/images/5/55/Priority_Low.png",
  2: "https://temtem.wiki.gg/images/b/b8/Priority_Normal.png",
  3: "https://temtem.wiki.gg/images/d/d7/Priority_High.png",
  4: "https://temtem.wiki.gg/images/7/73/Priority_VeryHigh.png",
  5: "https://temtem.wiki.gg/images/9/9f/Priority_Ultra.png",
};

export const TECH_CLASS_ICON_URLS: Record<Class, string> = {
  physical: "https://temtem.wiki.gg/images/e/ef/Physical.png",
  special: "https://temtem.wiki.gg/images/2/24/Special.png",
  status: "https://temtem.wiki.gg/images/d/d0/Status.png",
};
