import { TypeMatchupSquare, TypeMatchups } from "./augmented-types/temtems";
import matchupAlteringTraitsJSON from "./special-case-data/matchup-altering-traits.json";

export const typeMatchupSquare: TypeMatchupSquare = {
  Neutral: {
    Neutral: 1,
    Wind: 1,
    Earth: 1,
    Water: 1,
    Fire: 1,
    Nature: 1,
    Electric: 1,
    Mental: 0.5,
    Digital: 1,
    Melee: 1,
    Crystal: 1,
    Toxic: 1,
  },
  Wind: {
    Neutral: 1,
    Wind: 0.5,
    Earth: 1,
    Water: 1,
    Fire: 1,
    Nature: 1,
    Electric: 0.5,
    Mental: 1,
    Digital: 1,
    Melee: 1,
    Crystal: 1,
    Toxic: 2,
  },
  Earth: {
    Neutral: 1,
    Wind: 0.5,
    Earth: 1,
    Water: 0.5,
    Fire: 2,
    Nature: 0.5,
    Electric: 2,
    Mental: 1,
    Digital: 1,
    Melee: 1,
    Crystal: 2,
    Toxic: 1,
  },
  Water: {
    Neutral: 1,
    Wind: 1,
    Earth: 2,
    Water: 0.5,
    Fire: 2,
    Nature: 0.5,
    Electric: 1,
    Mental: 1,
    Digital: 2,
    Melee: 1,
    Crystal: 1,
    Toxic: 0.5,
  },
  Fire: {
    Neutral: 1,
    Wind: 1,
    Earth: 0.5,
    Water: 0.5,
    Fire: 0.5,
    Nature: 2,
    Electric: 1,
    Mental: 1,
    Digital: 1,
    Melee: 1,
    Crystal: 2,
    Toxic: 1,
  },
  Nature: {
    Neutral: 1,
    Wind: 1,
    Earth: 2,
    Water: 2,
    Fire: 0.5,
    Nature: 0.5,
    Electric: 1,
    Mental: 1,
    Digital: 1,
    Melee: 1,
    Crystal: 1,
    Toxic: 0.5,
  },
  Electric: {
    Neutral: 1,
    Wind: 2,
    Earth: 0.5,
    Water: 2,
    Fire: 1,
    Nature: 0.5,
    Electric: 0.5,
    Mental: 2,
    Digital: 2,
    Melee: 1,
    Crystal: 0.5,
    Toxic: 1,
  },
  Mental: {
    Neutral: 2,
    Wind: 1,
    Earth: 1,
    Water: 1,
    Fire: 1,
    Nature: 1,
    Electric: 1,
    Mental: 1,
    Digital: 1,
    Melee: 2,
    Crystal: 0.5,
    Toxic: 1,
  },
  Digital: {
    Neutral: 1,
    Wind: 1,
    Earth: 1,
    Water: 1,
    Fire: 1,
    Nature: 1,
    Electric: 1,
    Mental: 2,
    Digital: 2,
    Melee: 2,
    Crystal: 1,
    Toxic: 1,
  },
  Melee: {
    Neutral: 1,
    Wind: 1,
    Earth: 2,
    Water: 1,
    Fire: 1,
    Nature: 1,
    Electric: 1,
    Mental: 0.5,
    Digital: 1,
    Melee: 0.5,
    Crystal: 2,
    Toxic: 1,
  },
  Crystal: {
    Neutral: 1,
    Wind: 1,
    Earth: 0.5,
    Water: 1,
    Fire: 0.5,
    Nature: 1,
    Electric: 2,
    Mental: 2,
    Digital: 1,
    Melee: 1,
    Crystal: 1,
    Toxic: 1,
  },
  Toxic: {
    Neutral: 1,
    Wind: 1,
    Earth: 0.5,
    Water: 2,
    Fire: 1,
    Nature: 2,
    Electric: 1,
    Mental: 1,
    Digital: 0.5,
    Melee: 1,
    Crystal: 0.5,
    Toxic: 0.5,
  },
};

export const matchupAlteringTraits = new Map(
  matchupAlteringTraitsJSON.map((object) => {
    return [object.trait, object.modifier as TypeMatchups];
  })
);

// export const temTypes: TemTypeMap = {
//   neutral: {
//     index: 0,
//     imgUrl: "https://temtem.wiki.gg/images/b/b3/Neutral.png",
//     colors: {
//       base: "hsl(180, 52%, 94%)",
//       dark: "hsl(180, 52%, 34%)",
//       light: "hsl(180, 52%, 94%)",
//     },
//   },
//   wind: {
//     index: 1,
//     imgUrl: "https://temtem.wiki.gg/images/b/bf/Wind.png",
//     colors: {
//       base: "hsl(162, 96%, 51%)",
//       dark: "hsl(162, 96%, 21%)",
//       light: "hsl(162, 96%, 51%)",
//     },
//   },
//   earth: {
//     index: 2,
//     imgUrl: "https://temtem.wiki.gg/images/1/1e/Earth.png",
//     colors: {
//       base: "hsl(19, 41%, 55%)",
//       dark: "hsl(19, 41%, 25%)",
//       light: "hsl(19, 41%, 55%)",
//     },
//   },
//   water: {
//     index: 3,
//     imgUrl: "https://temtem.wiki.gg/images/9/9d/Water.png",
//     colors: {
//       base: "hsl(197, 100%, 64%)",
//       dark: "hsl(197, 100%, 24%)",
//       light: "hsl(197, 100%, 64%)",
//     },
//   },
//   fire: {
//     index: 4,
//     imgUrl: "https://temtem.wiki.gg/images/3/30/Fire.png",
//     colors: {
//       base: "hsl(5, 77%, 61%)",
//       dark: "hsl(5, 77%, 31%)",
//       light: "hsl(5, 77%, 61%)",
//     },
//   },
//   nature: {
//     index: 5,
//     imgUrl: "https://temtem.wiki.gg/images/a/a7/Nature.png",
//     colors: {
//       base: "hsl(89, 61%, 67%)",
//       dark: "hsl(89, 61%, 27%)",
//       light: "hsl(89, 61%, 67%)",
//     },
//   },
//   electric: {
//     index: 6,
//     imgUrl: "https://temtem.wiki.gg/images/2/2f/Electric.png",
//     colors: {
//       base: "hsl(47, 100%, 73%)",
//       dark: "hsl(47, 100%, 23%)",
//       light: "hsl(47, 100%, 73%)",
//     },
//   },
//   mental: {
//     index: 7,
//     imgUrl: "https://temtem.wiki.gg/images/b/bf/Mental.png",
//     colors: {
//       base: "hsl(321, 43%, 59%)",
//       dark: "hsl(321, 43%, 19%)",
//       light: "hsl(321, 43%, 59%)",
//     },
//   },
//   digital: {
//     index: 8,
//     imgUrl: "https://temtem.wiki.gg/images/1/1b/Digital.png",
//     colors: {
//       base: "hsl(182, 19%, 70%)",
//       dark: "hsl(182, 19%, 30%)",
//       light: "hsl(182, 19%, 70%)",
//     },
//   },
//   melee: {
//     index: 9,
//     imgUrl: "https://temtem.wiki.gg/images/8/8f/Melee.png",
//     colors: {
//       base: "hsl(19, 94%, 68%)",
//       dark: "hsl(19, 94%, 38%)",
//       light: "hsl(19, 94%, 68%)",
//     },
//   },
//   crystal: {
//     index: 10,
//     imgUrl: "https://temtem.wiki.gg/images/3/31/Crystal.png",
//     colors: {
//       base: "hsl(349, 79%, 60%)",
//       dark: "hsl(349, 79%, 30%)",
//       light: "hsl(349, 79%, 60%)",
//     },
//   },
//   toxic: {
//     index: 11,
//     imgUrl: "https://temtem.wiki.gg/images/9/96/Toxic.png",
//     colors: {
//       base: "hsl(300, 3%, 35%)",
//       dark: "hsl(300, 0%, 0%)",
//       light: "hsl(300, 3%, 35%)",
//     },
//   },
// };
